stages: # git push 之后要执行以下两个任务
  - master
  - build

prd_master: # 任务方法，命名方式必须是 prd_[任务名称]
  stage: master # 哪个stage会进来这里面
  tags:
    - master # 哪个tags会进来这里面，这个是在gitlab.com 的 CI/CD 配置的，就注册gitlab-runner所填写的tags
  only:
    - master # git的哪个分支有变化的时候能进来执行
  script:
    - ls -a
    - pwd
    - echo "CI" $CI
    - echo "CI_COMMIT_REF_NAME" $CI_COMMIT_REF_NAME
    - echo "CI_COMMIT_REF_SLUG" $CI_COMMIT_REF_SLUG
    - echo "CI_COMMIT_SHA" $CI_COMMIT_SHA
    - echo "CI_JOB_ID" $CI_JOB_ID
    - echo "CI_JOB_MANUAL" $CI_JOB_MANUAL
    - echo "CI_JOB_NAME" $CI_JOB_NAME
    - echo "CI_JOB_STAGE" $CI_JOB_STAGE
    - echo "CI_JOB_TOKEN" $CI_JOB_TOKEN
    - echo "CI_REPOSITORY_URL" $CI_REPOSITORY_URL
    - echo "CI_RUNNER_DESCRIPTION" $CI_RUNNER_DESCRIPTION
    - echo "CI_RUNNER_ID" $CI_RUNNER_ID
    - echo "CI_RUNNER_TAGS" $CI_RUNNER_TAGS
    - echo "CI_PIPELINE_ID" $CI_PIPELINE_ID
    - echo "CI_PIPELINE_TRIGGERED" $CI_PIPELINE_TRIGGERED
    - echo "CI_PROJECT_DIR" $CI_PROJECT_DIR
    - echo "CI_PROJECT_ID" $CI_PROJECT_ID
    - echo "CI_PROJECT_NAME" $CI_PROJECT_NAME
    - echo "CI_PROJECT_NAMESPACE" $CI_PROJECT_NAMESPACE
    - echo "CI_PROJECT_PATH" $CI_PROJECT_PATH
    - echo "CI_PROJECT_PATH_SLUG" $CI_PROJECT_PATH_SLUG
    - echo "CI_PROJECT_URL" $CI_PROJECT_URL
    - echo "CI_REGISTRY" $CI_REGISTRY
    - echo "CI_REGISTRY_IMAGE" $CI_REGISTRY_IMAGE
    - echo "CI_REGISTRY_PASSWORD" $CI_REGISTRY_PASSWORD
    - echo "CI_REGISTRY_USER" $CI_REGISTRY_USER
    - echo "CI_SERVER" $CI_SERVER
    - echo "CI_SERVER_NAME" $CI_SERVER_NAME
    - echo "CI_SERVER_REVISION" $CI_SERVER_REVISION
    - echo "CI_SERVER_VERSION" $CI_SERVER_VERSION
    - echo "ARTIFACT_DOWNLOAD_ATTEMPTS" $ARTIFACT_DOWNLOAD_ATTEMPTS
    - echo "GET_SOURCES_ATTEMPTS" $GET_SOURCES_ATTEMPTS
    - echo "GITLAB_CI" $GITLAB_CI
    - echo "GITLAB_USER_ID" $GITLAB_USER_ID
    - echo "GITLAB_USER_EMAIL" $GITLAB_USER_EMAIL
    - echo "RESTORE_CACHE_ATTEMPTS" $RESTORE_CACHE_ATTEMPTS

    - cd $CI_PROJECT_DIR # 该项目在服务器的绝对地址
    - npm i
    - npm run build
    - ls -a
  allow_failure: true

prd_build:
  stage: build
  tags:
    - master
  only:
    - master
  script:
    - pwd && ls -a
